import os

STORAGE_ACCOUNT = os.environ['STORAGE_ACCOUNT']
STORAGE_KEY = os.environ['STORAGE_KEY']
BIT_IMAGE_CONTAINER = os.environ['BIT_IMAGE_CONTAINER']
IS_EMULATED = False
GAME_CONFIG_TABLENAME = os.environ['GAME_CONFIG_TABLENAME']
GAME_CONFIG_PARTITIONKEY = os.environ['GAME_CONFIG_PARTITIONKEY']
GAME_CONFIG_ROWKEY = os.environ['GAME_CONFIG_ROWKEY']
PLAYER_TABLENAME = os.environ['PLAYER_TABLENAME']
PLAYER_IMG_TABLENAME = os.environ['PLAYER_IMG_TABLENAME']
PLAY_ATTEMPTS_TABLENAME = os.environ['PLAY_ATTEMPTS_TABLENAME']
BIT_IMAGE_SAS_URL = os.environ["BIT_IMAGE_SAS_URL"]